// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhnytzobqlvyqzdoibon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhobnl0em9icWx2eXF6ZG9pYm9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1Mzk3MDQsImV4cCI6MjA1MDExNTcwNH0.kuH-ZwgXNSl66MeVFfP_CWVoZQX4bhSDsRrYzsLl4pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);